### ISSUE TITLE
进入漫画阅读界面提示未知错误

### ISSUE THREAD

**Issue by JustinNick** [zhhr1122/z_comic_new#9]
进入漫画阅读界面提示未知错误java.lang.Throwable:发生了非网络异常，麻烦作者看下，

**Comment by wzmyyj** [comment]
我这也是这个错误。

**Comment by liwenpeng12** [comment]
我也报错了，下载和阅读都不行

**Comment by zhhr1122** [comment]
服务器网络不稳定，现在租用了一个免费的阿里云的服务器，用户一多就会这样。需要时不时重启一下
